# Generated by Django 3.2.15 on 2022-09-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=165, blank=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="municipalities", to="address.state"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Municipalities",
                "ordering": ("state", "name"),
                "unique_together": {("name", "state")},
            },
        ),
        migrations.AddField(
            model_name="locality",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="localities",
                to="address.municipality",
            ),
        ),
    ]
